import {
    FOOD_TOGGLE
} from '../constants/dietOptimizerConstants';

const init = {
    foods: [{
        food: 'Frozen_Broccoli',
        isSelected: true,
        pricePerServing: 0.16,
        servingSize: '10_Oz_Pkg',
        calories: 73.8,
        cholesterol: 0,
        totalFat: 0.8,
        sodium: 68.2,
        carbohydrates: 13.6,
        dietaryFiber: 8.5,
        protein: 8,
        vitA: 5867.4,
        vitC: 0.2,
        calcium: 159,
        iron: 2.3
    },

    {
        food: 'Raw_Carrots',
        isSelected: true,
        pricePerServing: 0.07,
        servingSize: '1/2_Cup_Shredded',
        calories: 23.7,
        cholesterol: 0,
        totalFat: 0.1,
        sodium: 19.2,
        carbohydrates: 5.6,
        dietaryFiber: 1.6,
        protein: .6,
        vitA: 15471,
        vitC: 5.1,
        calcium: 14.9,
        iron: 0.3
    },

    {
        food: 'Raw_Celery',
        isSelected: true,
        pricePerServing: 0.04,
        servingSize: '1_Stalk',
        calories: 6.4,
        cholesterol: 0,
        totalFat: 0.1,
        sodium: 34.8,
        carbohydrates: 1.5,
        dietaryFiber: 0.7,
        protein: .3,
        vitA: 53.6,
        vitC: 2.8,
        calcium: 16,
        iron: 0.2
    },

    {
        food: 'Frozen_Corn',
        isSelected: true,
        pricePerServing: 0.18,
        servingSize: '1/2_Cup',
        calories: 72.2,
        cholesterol: 0,
        totalFat: 0.6,
        sodium: 2.5,
        carbohydrates: 17.1,
        dietaryFiber: 2,
        protein: 2.5,
        vitA: 106.6,
        vitC: 5.2,
        calcium: 3.3,
        iron: 0.3
    },

    {
        food: 'Raw_Iceberg_Lettuce',
        isSelected: true,
        pricePerServing: 0.02,
        servingSize: '1_Leaf',
        calories: 2.6,
        cholesterol: 0,
        totalFat: 0,
        sodium: 1.8,
        carbohydrates: 0.4,
        dietaryFiber: 0.3,
        protein: .2,
        vitA: 66,
        vitC: 0.8,
        calcium: 3.8,
        iron: 0.1
    },

    {
        food: 'Raw_Sweet_Peppers',
        isSelected: true,
        pricePerServing: 0.53,
        servingSize: '1_Pepper',
        calories: 20,
        cholesterol: 0,
        totalFat: 0.1,
        sodium: 1.5,
        carbohydrates: 4.8,
        dietaryFiber: 1.3,
        protein: .7,
        vitA: 467.7,
        vitC: 66.1,
        calcium: 6.7,
        iron: 0.3
    },

    {
        food: 'Baked_Potatoes',
        isSelected: true,
        pricePerServing: 0.06,
        servingSize: '1/2_Cup',
        calories: 171.5,
        cholesterol: 0,
        totalFat: 0.2,
        sodium: 15.2,
        carbohydrates: 39.9,
        dietaryFiber: 3.2,
        protein: 3.7,
        vitA: 0,
        vitC: 15.6,
        calcium: 22.7,
        iron: 4.3
    },

    {
        food: 'Tofu',
        isSelected: true,
        pricePerServing: 0.31,
        servingSize: '1/4_block',
        calories: 88.2,
        cholesterol: 0,
        totalFat: 5.5,
        sodium: 8.1,
        carbohydrates: 2.2,
        dietaryFiber: 1.4,
        protein: 9.4,
        vitA: 98.6,
        vitC: 0.1,
        calcium: 121.8,
        iron: 6.2
    },

    {
        food: 'Roasted_Chicken',
        isSelected: true,
        pricePerServing: 0.84,
        servingSize: '1_lb_chicken',
        calories: 277.4,
        cholesterol: 129.9,
        totalFat: 10.8,
        sodium: 125.6,
        carbohydrates: 0,
        dietaryFiber: 0,
        protein: 42.2,
        vitA: 77.4,
        vitC: 0,
        calcium: 21.9,
        iron: 1.8
    },

    {
        food: 'Spaghetti_With_Sauce',
        isSelected: true,
        pricePerServing: 0.78,
        servingSize: '1_&_1/2_Cup',
        calories: 358.2,
        cholesterol: 0,
        totalFat: 12.3,
        sodium: 1237.1,
        carbohydrates: 58.3,
        dietaryFiber: 11.6,
        protein: 8.2,
        vitA: 3055.2,
        vitC: 27.9,
        calcium: 80.2,
        iron: 2.3
    },

    {
        food: 'Raw_Ripe_Red_Tomato',
        isSelected: true,
        pricePerServing: 0.27,
        servingSize: '1_Tomato_2-3/5_In',
        calories: 25.8,
        cholesterol: 0,
        totalFat: 0.4,
        sodium: 11.1,
        carbohydrates: 5.7,
        dietaryFiber: 1.4,
        protein: 1,
        vitA: 766.3,
        vitC: 23.5,
        calcium: 6.2,
        iron: 0.6
    },

    {
        food: 'Raw_Apple_With_Skin',
        isSelected: true,
        pricePerServing: 0.24,
        servingSize: '1_Fruit_3/Lb_Wo/Rf',
        calories: 81.4,
        cholesterol: 0,
        totalFat: 0.5,
        sodium: 0,
        carbohydrates: 21,
        dietaryFiber: 3.7,
        protein: .3,
        vitA: 73.1,
        vitC: 7.9,
        calcium: 9.7,
        iron: 0.2
    },

    {
        food: 'Banana',
        isSelected: true,
        pricePerServing: 0.15,
        servingSize: '1_Fruit_Wo/Skn_&_Seeds',
        calories: 104.9,
        cholesterol: 0,
        totalFat: 0.5,
        sodium: 1.1,
        carbohydrates: 26.7,
        dietaryFiber: 2.7,
        protein: 1.2,
        vitA: 92.3,
        vitC: 10.4,
        calcium: 6.8,
        iron: 0.4
    },

    {
        food: 'Grapes',
        isSelected: true,
        pricePerServing: 0.32,
        servingSize: '10_Fruits_Wo/Rf',
        calories: 15.1,
        cholesterol: 0,
        totalFat: 0.1,
        sodium: 0.5,
        carbohydrates: 4.1,
        dietaryFiber: 0.2,
        protein: .2,
        vitA: 24,
        vitC: 1,
        calcium: 3.4,
        iron: 0.1
    },

    {
        food: 'Fresh_Raw_Kiwifruit',
        isSelected: true,
        pricePerServing: 0.49,
        servingSize: '1_Med_Fruit_Wo/Skin',
        calories: 46.4,
        cholesterol: 0,
        totalFat: 0.3,
        sodium: 3.8,
        carbohydrates: 11.3,
        dietaryFiber: 2.6,
        protein: 0.8,
        vitA: 133,
        vitC: 74.5,
        calcium: 19.8,
        iron: 0.3
    },

    {
        food: 'Oranges',
        isSelected: true,
        pricePerServing: 0.15,
        servingSize: '1_Frt_2-5/8_Diam',
        calories: 61.6,
        cholesterol: 0,
        totalFat: 0.2,
        sodium: 0,
        carbohydrates: 15.4,
        dietaryFiber: 3.1,
        protein: 1.2,
        vitA: 268.6,
        vitC: 69.7,
        calcium: 52.4,
        iron: 0.1
    },

    {
        food: 'Bagels',
        isSelected: true,
        pricePerServing: 0.16,
        servingSize: '1_Oz',
        calories: 78,
        cholesterol: 0,
        totalFat: 0.5,
        sodium: 151.4,
        carbohydrates: 15.1,
        dietaryFiber: 0.6,
        protein: 3,
        vitA: 0,
        vitC: 0,
        calcium: 21,
        iron: 1
    },

    {
        food: 'Wheat_Bread',
        isSelected: true,
        pricePerServing: 0.05,
        servingSize: '1_Slice',
        calories: 65,
        cholesterol: 0,
        totalFat: 1,
        sodium: 134.5,
        carbohydrates: 12.4,
        dietaryFiber: 1.3,
        protein: 2.2,
        vitA: 0,
        vitC: 0,
        calcium: 10.8,
        iron: 0.7
    },

    {
        food: 'White_Bread',
        isSelected: true,
        pricePerServing: 0.06,
        servingSize: '1_Slice',
        calories: 65,
        cholesterol: 0,
        totalFat: 1,
        sodium: 132.5,
        carbohydrates: 11.8,
        dietaryFiber: 1.1,
        protein: 2.3,
        vitA: 0,
        vitC: 0,
        calcium: 26.2,
        iron: 0.8
    },

    {
        food: 'Oatmeal_Cookies',
        isSelected: true,
        pricePerServing: 0.09,
        servingSize: '1_Cookie',
        calories: 81,
        cholesterol: 0,
        totalFat: 3.3,
        sodium: 68.9,
        carbohydrates: 12.4,
        dietaryFiber: 0.6,
        protein: 1.1,
        vitA: 2.9,
        vitC: 0.1,
        calcium: 6.7,
        iron: 0.5
    },

    {
        food: 'Apple_Pie',
        isSelected: false,
        pricePerServing: 0.16,
        servingSize: '1_Oz',
        calories: 67.2,
        cholesterol: 0,
        totalFat: 3.1,
        sodium: 75.4,
        carbohydrates: 9.6,
        dietaryFiber: 0.5,
        protein: .5,
        vitA: 35.2,
        vitC: 0.9,
        calcium: 3.1,
        iron: 0.1
    },

    {
        food: 'Chocolate_Chip_Cookies',
        isSelected: false,
        pricePerServing: 0.03,
        servingSize: '1_Cookie',
        calories: 78.1,
        cholesterol: 5.1,
        totalFat: 4.5,
        sodium: 57.8,
        carbohydrates: 9.3,
        dietaryFiber: 0,
        protein: .9,
        vitA: 101.8,
        vitC: 0,
        calcium: 6.2,
        iron: 0.4
    },

    {
        food: 'Regular_Butter',
        isSelected: false,
        pricePerServing: 0.05,
        servingSize: '1_Pat',
        calories: 35.8,
        cholesterol: 10.9,
        totalFat: 4.1,
        sodium: 41.3,
        carbohydrates: 0,
        dietaryFiber: 0,
        protein: 0,
        vitA: 152.9,
        vitC: 0,
        calcium: 1.2,
        iron: 0
    },

    {
        food: 'Cheddar_Cheese',
        isSelected: false,
        pricePerServing: 0.25,
        servingSize: '1_Oz',
        calories: 112.7,
        cholesterol: 29.4,
        totalFat: 9.3,
        sodium: 173.7,
        carbohydrates: 0.4,
        dietaryFiber: 0,
        protein: 7,
        vitA: 296.5,
        vitC: 0,
        calcium: 202,
        iron: 0.2
    },

    {
        food: 'Whole_Milk_3.3%_Fat',
        isSelected: false,
        pricePerServing: 0.16,
        servingSize: '1_C',
        calories: 149.9,
        cholesterol: 33.2,
        totalFat: 8.1,
        sodium: 119.6,
        carbohydrates: 11.4,
        dietaryFiber: 0,
        protein: 8,
        vitA: 307.4,
        vitC: 2.3,
        calcium: 291.3,
        iron: 0.1
    },

    {
        food: '2%_Low_Fat_Milk',
        isSelected: false,
        pricePerServing: 0.23,
        servingSize: '1_C',
        calories: 121.2,
        cholesterol: 18.3,
        totalFat: 4.7,
        sodium: 121.8,
        carbohydrates: 11.7,
        dietaryFiber: 0,
        protein: 8.1,
        vitA: 500.2,
        vitC: 2.3,
        calcium: 296.7,
        iron: 0.1
    },

    {
        food: 'Skim_Milk',
        isSelected: false,
        pricePerServing: 0.13,
        servingSize: '1_C',
        calories: 85.5,
        cholesterol: 4.4,
        totalFat: 0.4,
        sodium: 126.2,
        carbohydrates: 11.9,
        dietaryFiber: 0,
        protein: 8.4,
        vitA: 499.8,
        vitC: 2.4,
        calcium: 302.3,
        iron: 0.1
    },

    {
        food: 'Poached_Eggs',
        isSelected: false,
        pricePerServing: 0.08,
        servingSize: 'Lrg_Egg',
        calories: 74.5,
        cholesterol: 211.5,
        totalFat: 5,
        sodium: 140,
        carbohydrates: 0.6,
        dietaryFiber: 0,
        protein: 6.2,
        vitA: 316,
        vitC: 0,
        calcium: 24.5,
        iron: 0.7
    },

    {
        food: 'Scrambled_Eggs',
        isSelected: false,
        pricePerServing: 0.11,
        servingSize: '1_Egg',
        calories: 99.6,
        cholesterol: 211.2,
        totalFat: 7.3,
        sodium: 168,
        carbohydrates: 1.3,
        dietaryFiber: 0,
        protein: 6.7,
        vitA: 409.2,
        vitC: 0.1,
        calcium: 42.6,
        iron: 0.7
    },

    {
        food: 'Turkey_Bologna',
        isSelected: false,
        pricePerServing: 0.15,
        servingSize: '1_Oz',
        calories: 56.4,
        cholesterol: 28.1,
        totalFat: 4.3,
        sodium: 248.9,
        carbohydrates: 0.3,
        dietaryFiber: 0,
        protein: 3.9,
        vitA: 0,
        vitC: 0,
        calcium: 23.8,
        iron: 0.4
    },

    {
        food: 'Beef_Frankfurter',
        isSelected: false,
        pricePerServing: 0.27,
        servingSize: '1_Frankfurter',
        calories: 141.8,
        cholesterol: 27.4,
        totalFat: 12.8,
        sodium: 461.7,
        carbohydrates: 0.8,
        dietaryFiber: 0,
        protein: 5.4,
        vitA: 0,
        vitC: 10.8,
        calcium: 9,
        iron: 0.6
    },

    {
        food: 'Extralean_Sliced_Ham',
        isSelected: false,
        pricePerServing: 0.33,
        servingSize: '1_Sl_6-1/4x4x1/16_In',
        calories: 37.1,
        cholesterol: 13.3,
        totalFat: 1.4,
        sodium: 405.1,
        carbohydrates: 0.3,
        dietaryFiber: 0,
        protein: 5.5,
        vitA: 0,
        vitC: 7.4,
        calcium: 2,
        iron: 0.2
    },

    {
        food: 'Pork_Kielbasa',
        isSelected: false,
        pricePerServing: 0.15,
        servingSize: '1_Sl_6x3-3/4x1/16_In',
        calories: 80.6,
        cholesterol: 17.4,
        totalFat: 7.1,
        sodium: 279.8,
        carbohydrates: 0.6,
        dietaryFiber: 0,
        protein: 3.4,
        vitA: 0,
        vitC: 5.5,
        calcium: 11.4,
        iron: 0.4
    },

    {
        food: 'Cap\'N_Crunch',
        isSelected: false,
        pricePerServing: 0.31,
        servingSize: '1_Oz',
        calories: 119.6,
        cholesterol: 0,
        totalFat: 2.6,
        sodium: 213.3,
        carbohydrates: 23,
        dietaryFiber: 0.5,
        protein: 1.4,
        vitA: 40.6,
        vitC: 0,
        calcium: 4.8,
        iron: 7.5
    },

    {
        food: 'Cheerios',
        isSelected: false,
        pricePerServing: 0.28,
        servingSize: '1_Oz',
        calories: 111,
        cholesterol: 0,
        totalFat: 1.8,
        sodium: 307.6,
        carbohydrates: 19.6,
        dietaryFiber: 2,
        protein: 4.3,
        vitA: 1252.2,
        vitC: 15.1,
        calcium: 48.6,
        iron: 4.5
    },

    {
        food: 'Corn_Flks_Kellogg\'S',
        isSelected: false,
        pricePerServing: 0.28,
        servingSize: '1_Oz',
        calories: 110.5,
        cholesterol: 0,
        totalFat: 0.1,
        sodium: 290.5,
        carbohydrates: 24.5,
        dietaryFiber: 0.7,
        protein: 2.3,
        vitA: 1252.2,
        vitC: 15.1,
        calcium: 0.9,
        iron: 1.8
    },

    {
        food: 'Raisin_Brn_Kellg\'S',
        isSelected: false,
        pricePerServing: 0.34,
        servingSize: '1.3_Oz',
        calories: 115.1,
        cholesterol: 0,
        totalFat: 0.7,
        sodium: 204.4,
        carbohydrates: 27.9,
        dietaryFiber: 4,
        protein: 4,
        vitA: 1250.2,
        vitC: 0,
        calcium: 12.9,
        iron: 16.8
    },

    {
        food: 'Rice_Krispies',
        isSelected: false,
        pricePerServing: 0.32,
        servingSize: '1_Oz',
        calories: 112.2,
        cholesterol: 0,
        totalFat: 0.2,
        sodium: 340.8,
        carbohydrates: 24.8,
        dietaryFiber: 0.4,
        protein: 1.9,
        vitA: 1252.2,
        vitC: 15.1,
        calcium: 4,
        iron: 1.8
    },

    {
        food: 'Special K',
        isSelected: false,
        pricePerServing: 0.38,
        servingSize: '1_Oz',
        calories: 110.8,
        cholesterol: 0,
        totalFat: 0.1,
        sodium: 265.5,
        carbohydrates: 21.3,
        dietaryFiber: 0.7,
        protein: 5.6,
        vitA: 1252.2,
        vitC: 15.1,
        calcium: 8.2,
        iron: 4.5
    },

    {
        food: 'Oatmeal',
        isSelected: false,
        pricePerServing: 0.82,
        servingSize: '1_C',
        calories: 145.1,
        cholesterol: 0,
        totalFat: 2.3,
        sodium: 2.3,
        carbohydrates: 25.3,
        dietaryFiber: 4,
        protein: 6.1,
        vitA: 37.4,
        vitC: 0,
        calcium: 18.7,
        iron: 1.6
    },

    {
        food: 'Malt-OMeal_Choc',
        isSelected: false,
        pricePerServing: 0.52,
        servingSize: '1_C',
        calories: 607.2,
        cholesterol: 0,
        totalFat: 1.5,
        sodium: 16.5,
        carbohydrates: 128.2,
        dietaryFiber: 0,
        protein: 17.3,
        vitA: 0,
        vitC: 0,
        calcium: 23.1,
        iron: 47.2
    },

    {
        food: 'Pizza_W/Pepperoni',
        isSelected: false,
        pricePerServing: 0.44,
        servingSize: '1_Slice',
        calories: 181,
        cholesterol: 14.2,
        totalFat: 7,
        sodium: 267,
        carbohydrates: 19.9,
        dietaryFiber: 0,
        protein: 10.1,
        vitA: 281.9,
        vitC: 1.6,
        calcium: 64.6,
        iron: 0.9
    },

    {
        food: 'Taco',
        isSelected: false,
        pricePerServing: 0.59,
        servingSize: '1_Small_Taco',
        calories: 369.4,
        cholesterol: 56.4,
        totalFat: 20.6,
        sodium: 802,
        carbohydrates: 26.7,
        dietaryFiber: 0,
        protein: 20.7,
        vitA: 855,
        vitC: 2.2,
        calcium: 220.6,
        iron: 2.4
    },

    {
        food: 'Hamburger_W/Toppings',
        isSelected: false,
        pricePerServing: 0.83,
        servingSize: '1_Burger',
        calories: 275,
        cholesterol: 42.8,
        totalFat: 10.2,
        sodium: 563.9,
        carbohydrates: 32.7,
        dietaryFiber: 0,
        protein: 13.6,
        vitA: 126.3,
        vitC: 2.6,
        calcium: 51.4,
        iron: 2.5
    },

    {
        food: 'Plain_Hotdog',
        isSelected: false,
        pricePerServing: 0.31,
        servingSize: '1_Hotdog',
        calories: 242.1,
        cholesterol: 44.1,
        totalFat: 14.5,
        sodium: 670.3,
        carbohydrates: 18,
        dietaryFiber: 0,
        protein: 10.4,
        vitA: 0,
        vitC: 0.1,
        calcium: 23.5,
        iron: 2.3
    },

    {
        food: 'Couscous',
        isSelected: false,
        pricePerServing: 0.39,
        servingSize: '1/2_Cup',
        calories: 100.8,
        cholesterol: 0,
        totalFat: 0.1,
        sodium: 4.5,
        carbohydrates: 20.9,
        dietaryFiber: 1.3,
        protein: 3.4,
        vitA: 0,
        vitC: 0,
        calcium: 7.2,
        iron: 0.3
    },

    {
        food: 'White_Rice',
        isSelected: false,
        pricePerServing: 0.08,
        servingSize: '1/2_Cup',
        calories: 102.7,
        cholesterol: 0,
        totalFat: 0.2,
        sodium: 0.8,
        carbohydrates: 22.3,
        dietaryFiber: 0.3,
        protein: 2.1,
        vitA: 0,
        vitC: 0,
        calcium: 7.9,
        iron: 0.9
    },

    {
        food: 'Macaroni_Ckd',
        isSelected: false,
        pricePerServing: 0.17,
        servingSize: '1/2_Cup',
        calories: 98.7,
        cholesterol: 0,
        totalFat: 0.5,
        sodium: 0.7,
        carbohydrates: 19.8,
        dietaryFiber: 0.9,
        protein: 3.3,
        vitA: 0,
        vitC: 0,
        calcium: 4.9,
        iron: 1
    },

    {
        food: 'Peanut_Butter',
        isSelected: false,
        pricePerServing: 0.07,
        servingSize: '2_Tbsp',
        calories: 188.5,
        cholesterol: 0,
        totalFat: 16,
        sodium: 155.5,
        carbohydrates: 6.9,
        dietaryFiber: 2.1,
        protein: 7.7,
        vitA: 0,
        vitC: 0,
        calcium: 13.1,
        iron: 0.6
    },

    {
        food: 'Pork',
        isSelected: false,
        pricePerServing: 0.81,
        servingSize: '4_Oz',
        calories: 710.8,
        cholesterol: 105.1,
        totalFat: 72.2,
        sodium: 38.4,
        carbohydrates: 0,
        dietaryFiber: 0,
        protein: 13.8,
        vitA: 14.7,
        vitC: 0,
        calcium: 59.9,
        iron: 0.4
    },

    {
        food: 'Sardines_in_Oil',
        isSelected: false,
        pricePerServing: 0.45,
        servingSize: '2_Sardines',
        calories: 49.9,
        cholesterol: 34.1,
        totalFat: 2.7,
        sodium: 121.2,
        carbohydrates: 0,
        dietaryFiber: 0,
        protein: 5.9,
        vitA: 53.8,
        vitC: 0,
        calcium: 91.7,
        iron: 0.7
    },

    {
        food: 'White_Tuna_in_Water',
        isSelected: false,
        pricePerServing: 0.69,
        servingSize: '3_Oz',
        calories: 115.6,
        cholesterol: 35.7,
        totalFat: 2.1,
        sodium: 333.2,
        carbohydrates: 0,
        dietaryFiber: 0,
        protein: 22.7,
        vitA: 68,
        vitC: 0,
        calcium: 3.4,
        iron: 0.5
    },

    {
        food: 'Popcorn_AirPopped',
        isSelected: false,
        pricePerServing: 0.04,
        servingSize: '1_Oz',
        calories: 108.3,
        cholesterol: 0,
        totalFat: 1.2,
        sodium: 1.1,
        carbohydrates: 22.1,
        dietaryFiber: 4.3,
        protein: 3.4,
        vitA: 55.6,
        vitC: 0,
        calcium: 2.8,
        iron: 0.8
    },

    {
        food: 'Potato_Chips_Bbqflvr',
        isSelected: false,
        pricePerServing: 0.22,
        servingSize: '1_Oz',
        calories: 139.2,
        cholesterol: 0,
        totalFat: 9.2,
        sodium: 212.6,
        carbohydrates: 15,
        dietaryFiber: 1.2,
        protein: 2.2,
        vitA: 61.5,
        vitC: 9.6,
        calcium: 14.2,
        iron: 0.5
    },

    {
        food: 'Pretzels',
        isSelected: false,
        pricePerServing: 0.12,
        servingSize: '1_Oz',
        calories: 108,
        cholesterol: 0,
        totalFat: 1,
        sodium: 486.2,
        carbohydrates: 22.5,
        dietaryFiber: 0.9,
        protein: 2.6,
        vitA: 0,
        vitC: 0,
        calcium: 10.2,
        iron: 1.2
    },

    {
        food: 'Tortilla_Chip',
        isSelected: false,
        pricePerServing: 0.19,
        servingSize: '1_Oz',
        calories: 142,
        cholesterol: 0,
        totalFat: 7.4,
        sodium: 149.7,
        carbohydrates: 17.8,
        dietaryFiber: 1.8,
        protein: 2,
        vitA: 55.6,
        vitC: 0,
        calcium: 43.7,
        iron: 0.4
    },

    {
        food: 'Chicken_Noodle_Soup',
        isSelected: false,
        pricePerServing: 0.39,
        servingSize: '1_C_(8_Fl_Oz)',
        calories: 150.1,
        cholesterol: 12.3,
        totalFat: 4.6,
        sodium: 1862.2,
        carbohydrates: 18.7,
        dietaryFiber: 1.5,
        protein: 7.9,
        vitA: 1308.7,
        vitC: 0,
        calcium: 27.1,
        iron: 1.5
    },

    {
        food: 'Spilt_Pea&Ham_Soup',
        isSelected: false,
        pricePerServing: 0.67,
        servingSize: '1_C_(8_Fl_Oz)',
        calories: 184.8,
        cholesterol: 7.2,
        totalFat: 4,
        sodium: 964.8,
        carbohydrates: 26.8,
        dietaryFiber: 4.1,
        protein: 11.1,
        vitA: 4872,
        vitC: 7,
        calcium: 33.6,
        iron: 2.1
    },

    {
        food: 'Vegetbeef_Soup',
        isSelected: false,
        pricePerServing: 0.71,
        servingSize: '1_C_(8_Fl_Oz)',
        calories: 158.1,
        cholesterol: 10,
        totalFat: 3.8,
        sodium: 1915.1,
        carbohydrates: 20.4,
        dietaryFiber: 4,
        protein: 11.2,
        vitA: 3785.1,
        vitC: 4.8,
        calcium: 32.6,
        iron: 2.2
    },

    {
        food: 'Neweng_Clamchwd',
        isSelected: false,
        pricePerServing: 0.75,
        servingSize: '1_C_(8_Fl_Oz)',
        calories: 175.7,
        cholesterol: 10,
        totalFat: 5,
        sodium: 1864.9,
        carbohydrates: 21.8,
        dietaryFiber: 1.5,
        protein: 10.9,
        vitA: 20.1,
        vitC: 4.8,
        calcium: 82.8,
        iron: 2.8
    },

    {
        food: 'Tomato_Soup',
        isSelected: false,
        pricePerServing: 0.39,
        servingSize: '1_C_(8_Fl_Oz)',
        calories: 170.7,
        cholesterol: 0,
        totalFat: 3.8,
        sodium: 1744.4,
        carbohydrates: 33.2,
        dietaryFiber: 1,
        protein: 4.1,
        vitA: 1393,
        vitC: 133,
        calcium: 27.6,
        iron: 3.5
    },

    {
        food: 'New_E_Clamchwd_W/_Mlk',
        isSelected: false,
        pricePerServing: 0.99,
        servingSize: '1_C_(8_Fl_Oz)',
        calories: 163.7,
        cholesterol: 22.3,
        totalFat: 6.6,
        sodium: 992,
        carbohydrates: 16.6,
        dietaryFiber: 1.5,
        protein: 9.5,
        vitA: 163.7,
        vitC: 3.5,
        calcium: 186,
        iron: 1.5
    },

    {
        food: 'Crm_Mshrm_Soup_W/Mlk',
        isSelected: false,
        pricePerServing: 0.65,
        servingSize: '1_C_(8_Fl_Oz)',
        calories: 203.4,
        cholesterol: 19.8,
        totalFat: 13.6,
        sodium: 1076.3,
        carbohydrates: 15,
        dietaryFiber: 0.5,
        protein: 6.1,
        vitA: 153.8,
        vitC: 2.2,
        calcium: 178.6,
        iron: 0.6
    },

    {
        food: 'Beanbacn_Soup_W/Wat',
        isSelected: false,
        pricePerServing: 0.67,
        servingSize: '1_C_(8_Fl_Oz)',
        calories: 172,
        cholesterol: 2.5,
        totalFat: 5.9,
        sodium: 951.3,
        carbohydrates: 22.8,
        dietaryFiber: 8.6,
        protein: 7.9,
        vitA: 888,
        vitC: 1.5,
        calcium: 81,
        iron: 2
    }]
};

const dietOptmizerReducer = (state = init, action) => {
    switch(action.type) {
        case FOOD_TOGGLE: {
            return Object.assign({}, state, {
                foods: state.foods.map(f => {
                    if(f.food === action.food) {
                        return Object.assign({}, f, {
                            isSelected: !f.isSelected
                        });
                    }

                    return f;
                })
            })
        }
        default: {}
    }

    return state;
};

export default dietOptmizerReducer;